
import csv

# -*- coding: utf-8 -*-
"""PyNicolas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U0O3fz32xmfK4Acg59bb6xR1hjDaPOx_
"""

# Sample waste data
data = [
    {"date": "2026-04-29", "location": "Cameroon", "waste_type": "plastic", "quantity_kg": 500},
    {"date": "2026-04-29", "location": "France", "waste_type": "biomass", "quantity_kg": -20},
    {"date": "2026-04-29", "location": "China", "waste_type": "plastic", "quantity_kg": 1000},
    {"date": "2026-04-29", "location": "", "waste_type": "agriculture", "quantity_kg": 300}
]

print("Raw Data:")
for item in data:
    print(item)

# Clean data
cleaned_data = []

for item in data:
    # Skip invalid quantity
    if item["quantity_kg"] <= 0:
        continue

    # Skip missing location
    if item["location"] == "":
        continue

    cleaned_data.append(item)

print("\nCleaned Data:")
for item in cleaned_data:
    print(item)

# Clean and validate data
cleaned_data = []

print("\nValidation Process:")

for item in data:
    if item["quantity_kg"] <= 0:
        print(f"Removed invalid quantity: {item}")
        continue

    if item["location"] == "":
        print(f"Removed missing location: {item}")
        continue

    cleaned_data.append(item)

print("\nCleaned Data:")
for item in cleaned_data:
    print(item)

# Summary
total_records = len(data)
clean_records = len(cleaned_data)

print("\nSummary:")
print(f"Total records: {total_records}")
print(f"Clean records: {clean_records}")
print(f"Removed records: {total_records - clean_records}")

# Save cleaned data to CSV
with open("cleaned_waste_data.csv", "w", newline="") as file:
    fieldnames = ["date", "location", "waste_type", "quantity_kg"]
    writer = csv.DictWriter(file, fieldnames=fieldnames)

    writer.writeheader()
    writer.writerows(cleaned_data)

print("\nCleaned data saved to cleaned_waste_data.csv")


# Data Quality Score
quality_score = (clean_records / total_records) * 100

print(f"\nData Quality Score: {quality_score:.2f}%")

# Save quality report
with open("quality_report.txt", "w") as file:
    file.write("Waste Data Quality Report\n")
    file.write("-------------------------\n")
    file.write(f"Total records: {total_records}\n")
    file.write(f"Clean records: {clean_records}\n")
    file.write(f"Removed records: {total_records - clean_records}\n")
    file.write(f"Data Quality Score: {quality_score:.2f}%\n")

print("Quality report saved to quality_report.txt")